language: ruby

rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head

brefore_install:
  - sudo apt-get update
  - sudo apt-get install libpng-dev libjpeg-dev

script:
  - bundle exec rake compile
  - bundle exec rake test
